Change boundary conditions. Update Allrun script

diff --git a/test/Allrun b/test/Allrun
--- a/test/Allrun
+++ b/test/Allrun
@@ -4,12 +4,23 @@ cd ${0%/*} || exit 1    # Run from this directory
 # Source tutorial run functions
 . $WM_PROJECT_DIR/bin/tools/RunFunctions
 
-runApplication blockMesh
+# Run a command and check its exit code.
+run_and_check() {
+    runApplication $1 $2
 
-runApplication checkMesh
+    if ! [ $? = 0 ];
+    then
+        echo "$1 failed!"
+        exit 1
+    fi
+}
 
-runApplication foamRun
+run_and_check blockMesh
 
-runApplication paraFoam -touch
+run_and_check checkMesh
+
+run_and_check foamRun
+
+run_and_check paraFoam -touch
 
 #------------------------------------------------------------------------------
